### ISSUE TITLE
Support for Complex Matrices in Proximal Solvers?

### ISSUE THREAD

**Issue by sihan-shao** [princeton-computational-imaging/Delta-Prox#1]
Hi, 

Does the current implementation of the differentiable proximal solver support complex number computations inherently? Can these differentiable proximal solvers handle complex linear problems, like

**y = Ax**

where **y**, **A** and **x** are complex matrices.  

Thank you for your time and this valuable work.

**Comment by Vandermode** [comment]
@Zeqiang-Lai could you give some comments on this question? I think supporting complex number operations in DeltaProx is easy if not implemented. See our CS-MRI example where the observation y is complex vector generated by subsampled Fourier transform

**Comment by Zeqiang-Lai** [comment]
I am not familiar with user cases that requires complex matrices for y, A, x. 

Basically, the computation in Delta Prox solely rely on the definition of linear operators and proximal functions, so it is easy to extend Delta Prox for complex computation by writing custom linear operators and proximal functions that accept complex matrices. 

For current implementation, most linear operators are defined for real matrices, but there are some proximal functions that outputs complex matrices such as CS-MRI (as discussed by @Vandermode )
