### ISSUE TITLE
Can you provide a version that is compatible with MacBook M1, M2, or M3?

### ISSUE THREAD

**Issue by Jiebo-2020** [princeton-computational-imaging/Delta-Prox#2]

**Comment by Vandermode** [comment]
Our codebase mainly relies on Pytorch. If you can install that in your local computer, it should work well.

**Comment by Zeqiang-Lai** [comment]
Do you mean mps acceleration for m1/2/3 chips? I think CPU mode should work out-of-box, if you have encountered any errors, could you share the log for us?

**Comment by Jiebo-2020** [comment]
Yes, I had several issues when running it with MPS. Firstly, it utilizes CUDA, and I needed to convert all CUDA instances to MPS style. Additionally, there was a problem with complex floats. MPS doesn't support all types of data. For example, in torch.fft.fftn and torch.fft.ifftn, I calculated all Fourier transform functions on 'CPU.' After making these changes, it works. Currently, I have already fixed all issues that related to MPS. My Mac is an M3 Max, equipped with the latest PyTorch packages. Thank you! If you need my modified dprox package, I can email it to you.
